name: Update the Postman collection

on:
  push:
    branches:
      - main

jobs:
  update-postman:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Validate and Process Postman Collections
        run: |
          echo "Validating Postman Collections..."
          # Add commands to validate and process your Postman collections
          # For example, using Newman:
          newman run ./Chat_Generation/Chat_generate.postman_collection.json || exit 1
          newman run ./Text_Generation/Text_generate.postman_collection.json || exit 1
          newman run ./Code_Execution/Code_Exec.postman_collection.json || exit 1
        env:
          POSTMAN_API_KEY: ${{ secrets.POSTMANAPIKEY }}

      - name: Handle Errors
        if: failure()
        run: |
          echo "Error processing one or more Postman collections."
          exit 1